const amazonOffers = {
  products: [
    {
      title: "One Piece 3 em 1 Vol. 1",
      author: "Eiichiro Oda",
      price: "R$ 38,34",
      discount: "R$ 49,90",
      imageUrl: "https://m.media-amazon.com/images/I/61xOtH1kTsL._SY466_.jpg",
      link: "https://amzn.to/3XmkXto",
    },
    {
      title: "Box Demon Slayer Vols. 1 ao 23",
      author: "Koyoharu Gotouge",
      price: "R$ 637,42",
      discount: "R$ 749,90",
      imageUrl: "https://m.media-amazon.com/images/I/61nMg7xGQTL.AC_UY218.jpg",
      link: "https://amzn.to/3VMHONB",
    },
    {
      title: "Frieren e a Jornada para o Além - 01",
      author: "Kanehito Yamada e Tsukasa Abe",
      price: "R$ 26,10",
      discount: "R$ 34,90",
      imageUrl: "https://m.media-amazon.com/images/I/71VnRnDjc8L.AC_UY218.jpg",
      link: "https://amzn.to/3xoyplU",
    },
    {
      title: "Um Sinal de Afeto: Volume 1",
      author: "Suu Morishita",
      price: "R$ 31,36",
      discount: "R$ 36,90",
      imageUrl: "https://m.media-amazon.com/images/I/81AmkU9Gg9L.AC_UY218.jpg",
      link: "https://amzn.to/3VLVng3",
    },
    {
      title: "Monster Kanzenban Vol. 1",
      author: "Naoki Urasawa",
      price: "R$ 85,90",
      discount: "R$ 99,90",
      imageUrl: "https://m.media-amazon.com/images/I/81VI6wwVzVL.AC_UY218.jpg",
      link: "https://amzn.to/3VLHxKN",
    },
    {
      title: "Boa Noite Punpun - Vol. 1",
      author: "Inio Asano",
      price: "R$ 43,56",
      discount: "R$ 59,90",
      imageUrl: "https://m.media-amazon.com/images/I/51EQ5jMPsHL.AC_UY218.jpg",
      link: "https://amzn.to/4b4Zf05",
    },
    {
      title: "Fairy Tail - Vol. 1",
      author: "Hiro Mashima",
      price: "R$ 16,95",
      discount: "R$ 33,90",
      imageUrl: "https://m.media-amazon.com/images/I/71xRG90fDeL.AC_UY218.jpg",
      link: "https://amzn.to/45qILOJ",
    },
    {
      title: "Quero comer seu Pâncreas (Livro)",
      author: "Yoru Sumino",
      price: "R$ 24,95",
      discount: "R$ 49,90",
      imageUrl: "https://m.media-amazon.com/images/I/81zvVtQQnRL.AC_UY218.jpg",
      link: "https://amzn.to/4b9noTt",
    },
    {
      title: "Nana Vol.01",
      author: "Ai Yazawa",
      price: "R$ 19,19",
      discount: "R$ 33,90",
      imageUrl: "https://m.media-amazon.com/images/I/810RyhfkR7L.AC_UY218.jpg",
      link: "https://amzn.to/3zeGOc0",
    },
    {
      title: "Dragon Ball Gaiden 01 - Aquela vez que reencarnei como Yamcha",
      author: "Akira Toriyama",
      price: "R$ 23,99",
      discount: "R$ 36,90",
      imageUrl: "https://m.media-amazon.com/images/I/619-wdwHpwL.AC_UY218.jpg",
      link: "https://amzn.to/45skSX8",
    },
    {
      title: "Bleach Remix - 01",
      author: "Tite Kubo",
      price: "R$ 53,66",
      discount: "R$ 64,90",
      imageUrl: "https://m.media-amazon.com/images/I/51pAoyagkWL.AC_UY218.jpg",
      link: "https://amzn.to/3z7UDJv",
    },
    {
      title: "Anohana - Vol. 1",
      author: "Cho-Heiwa Buster",
      price: "R$ 24,13",
      discount: "R$ 37,90",
      imageUrl: "https://m.media-amazon.com/images/I/611K3vX6FbL.AC_UY218.jpg",
      link: "https://amzn.to/3VLTno6",
    },
    {
      title: "Yona - A Princesa do Alvorecer - BIG - Vol. 01",
      author: "Mizuho Kusanagi",
      price: "R$ 29,60",
      discount: "R$ 54,90",
      imageUrl: "https://m.media-amazon.com/images/I/61T5wd7oBVL.AC_UY218.jpg",
      link: "https://amzn.to/3XsIatP",
    },
    {
      title: "Little Witch Academia - Vol. 1",
      author: "Trigger, Yoh Yoshinari, e outros.",
      price: "R$ 28,42",
      discount: "R$ 37,90",
      imageUrl: "https://m.media-amazon.com/images/I/716HFNX9rFL.AC_UY218.jpg",
      link: "https://amzn.to/4c4tBB4",
    },
    {
      title: "As Flores do Mal (Aku no Hana) - Volume 03",
      author: "Shuzo Oshimi",
      price: "R$ 10,01",
      discount: "R$ 26,90",
      imageUrl: "https://m.media-amazon.com/images/I/71-pNmNANWL.AC_UY218.jpg",
      link: "https://amzn.to/3XtWBOu",
    },
    {
      title: "My Hero Academia - Boku no Hero - Vol. 33",
      author: "Kohei Horikoshi",
      price: "R$ 18,49",
      discount: "R$ 37,90",
      imageUrl: "https://m.media-amazon.com/images/I/61ViAZFsJhL.AC_UY218.jpg",
      link: "https://amzn.to/3XsuWxf",
    },
    {
      title: "Contos de Horror da Mimi (Edição Completa)",
      author: "Junji Ito",
      price: "R$ 49,08",
      discount: "R$ 69,90",
      imageUrl: "https://m.media-amazon.com/images/I/81MbAANFXFL.AC_UY218.jpg",
      link: "https://amzn.to/4c27viU",
    },
  ],
};

export default amazonOffers;
